version="0.3.2"

[scripts]
test = "cargo test %% -- --test-threads 1"
test-print = "cargo test %% -- --nocapture --test-threads 1"
clippy = "cargo clippy -- -D warnings"
run = "cargo run -- -c tmp/config.yml"

[scripts.check]
cmd = "cargo check && cargo fmt -- --check && cargo clippy && cargo test -- --test-threads 1"
desc = "validates the code (same checks as on CI)"
