version = "0.3.2"

[scripts]
test = "RUST_BACKTRACE=1 REGENERATE_FIXTURE_IF_NOT_EXIST=1 cargo test %% -- --test-threads 1"
testp = "RUST_BACKTRACE=1 REGENERATE_FIXTURE_IF_NOT_EXIST=1  cargo test %% -- --nocapture --test-threads 1"
clippy = "cargo clippy -- -D warnings"
run = "cargo run -- -c local_configs/local.yml --jobs by_id_excluding_replica_updated_ats --tables users --diff-file tmp/all_users.diff"
fix = "cargo clippy --fix"
check = { cmd = "cargo check && cargo fmt -- --check && cargo clippy && cargo test -- --test-threads 1", desc = "validates the code (same checks as on CI)" }
squash = [
  "git reset $(git merge-base main $(git branch --show-current))",
  "git add -A",
  "git commit -m $(git rev-parse --abbrev-ref HEAD)",
]
