version = "0.3.2"

[scripts]
test = "RUST_BACKTRACE=1 cargo test %% -- --test-threads 1"
testp = "RUST_BACKTRACE=1 cargo test %% -- --nocapture --test-threads 1"
clippy = "cargo clippy -- -D warnings"
run = "cargo run -- -c local_configs/local.yml"
fix = "cargo clippy --fix"
check = { cmd = "cargo check && cargo fmt -- --check && cargo clippy && cargo test -- --test-threads 1", desc = "validates the code (same checks as on CI)" }
