[package]
name = "db-compare"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
clap = { version = "4.1.4", features = ["derive"] }
openssl = "0.10.45"
postgres = "0.19.4"
postgres-openssl = "0.5.0"
serde = "1.0.152"
serde_json = "1.0.91"
similar = "2.2.1"
yaml-rust = "0.4.5"
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls" , "postgres" ] }
tokio = { version = "1", features = ["full"] }
futures = "0.3.26"
